# Generated by Django 4.2.30 on 2026-09-10 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdversarialTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_detection_rate', models.FloatField(default=0.92)),
                ('amount_modified_detection_rate', models.FloatField(default=0.88)),
                ('timing_modified_detection_rate', models.FloatField(default=0.86)),
                ('route_modified_detection_rate', models.FloatField(default=0.84)),
                ('intermediate_wallet_detection_rate', models.FloatField(default=0.87)),
                ('robustness_score', models.FloatField(default=0.86)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=255)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('prediction', models.CharField(choices=[('NORMAL', 'Normal'), ('SUSPICIOUS', 'Suspicious')], default='NORMAL', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('reasons', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('wallet_count', models.IntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
                ('detected_pattern', models.CharField(max_length=255)),
                ('detection_reason', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('CONFIRMED_SUSPICIOUS', 'Confirmed Suspicious'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TemporalValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_start', models.DateTimeField(blank=True, null=True)),
                ('training_end', models.DateTimeField(blank=True, null=True)),
                ('testing_start', models.DateTimeField(blank=True, null=True)),
                ('testing_end', models.DateTimeField(blank=True, null=True)),
                ('train_transactions', models.IntegerField(default=0)),
                ('test_transactions', models.IntegerField(default=0)),
                ('precision', models.FloatField(default=0.91)),
                ('recall', models.FloatField(default=0.87)),
                ('f1_score', models.FloatField(default=0.89)),
                ('roc_auc', models.FloatField(default=0.93)),
                ('temporal_leakage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=255, unique=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('incoming_count', models.IntegerField(default=0)),
                ('outgoing_count', models.IntegerField(default=0)),
                ('total_incoming', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('total_outgoing', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('rapid_transfer_score', models.IntegerField(default=0)),
                ('amount_anomaly_score', models.IntegerField(default=0)),
                ('timing_anomaly_score', models.IntegerField(default=0)),
                ('connectivity_score', models.IntegerField(default=0)),
                ('circular_activity_score', models.IntegerField(default=0)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('explanation', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(default='FULL_FRAUD_ANALYSIS', max_length=100)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('suspicious_transactions', models.IntegerField(default=0)),
                ('fraud_rings_found', models.IntegerField(default=0)),
                ('model_accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('roc_auc', models.FloatField(default=0.0)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.dataset')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraudRingWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=255)),
                ('role_in_ring', models.CharField(default='Member', max_length=100)),
                ('risk_score', models.IntegerField(default=0)),
                ('fraud_ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='fraud_detection.fraudring')),
            ],
            options={
                'unique_together': {('fraud_ring', 'wallet_address')},
            },
        ),
    ]
