# Generated by Django 4.2.30 on 2026-09-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=255)),
                ('sender_wallet', models.CharField(db_index=True, max_length=255)),
                ('receiver_wallet', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('transaction_time', models.DateTimeField(db_index=True)),
                ('block_height', models.BigIntegerField(default=0)),
                ('fee', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('input_count', models.IntegerField(default=1)),
                ('output_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='datasets.dataset')),
            ],
            options={
                'indexes': [models.Index(fields=['sender_wallet'], name='transaction_sender__c33a71_idx'), models.Index(fields=['receiver_wallet'], name='transaction_receive_4471e0_idx'), models.Index(fields=['transaction_time'], name='transaction_transac_b2a781_idx'), models.Index(fields=['transaction_hash'], name='transaction_transac_6bf4ee_idx')],
            },
        ),
    ]
